version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api-backend
    ports:
      - "3333:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - ALLOWED_ORIGINS=http://localhost:3666,http://127.0.0.1:3666,http://192.168.0.164:3666,http://localhost:3333,http://127.0.0.1:3333,http://192.168.0.164:3333
    networks:
      - task-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-frontend
    ports:
      - "3666:80"
    environment:
      - NGINX_PORT=80
    networks:
      - task-network
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  task-network:
    driver: bridge
    name: task-management-network

volumes:
  # Optional: Add volumes if needed for data persistence
  app-data:
    name: task-management-data